name: "Install"
description: "Install python, then cache"
inputs:
  python-version:
    description: "Python version"
    required: true
  python-architecture:
    description: "Python architecture, if not default for platform"
  task:
    description: "Task name"
    required: true
runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }} ${{ inputs.python-architecture }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
      architecture: ${{ inputs.python-architecture }}
  - name: Restore cache
    uses: actions/cache@v3
    with:
      path: |
        .tox/
        ~/.cache
        ~/.local
        ~/appdata/local/pip/cache
        ~/Library/Caches/pip
        ~/wheelhouse
      key: deps-${{ runner.os }}-${{ hashFiles('requirements/*.txt') }}-${{ inputs.python-version }}-${{ inputs.python-architecture }}-${{ inputs.task }}
      restore-keys: |
        deps-${{ runner.os }}-${{ hashFiles('requirements/*.txt') }}-${{ inputs.python-version }}-${{ inputs.python-architecture }}
        deps-${{ runner.os }}-${{ hashFiles('requirements/*.txt') }}
        deps-${{ runner.os }}
